../../dut/src/float_and_fixed_pkg/fixed_float_types_c.vhd
../../dut/src/float_and_fixed_pkg/fixed_pkg_c.vhd
../../dut/src/float_and_fixed_pkg/float_pkg_c.vhd

../../dut/src/Include/constants_package.vhd
../../dut/src/Include/vpf_records.vhd
../../dut/src/Include/ports_package.vhd

../../dut/src/Filters/blur_filter.vhd
../../dut/src/Filters/blur_mac.vhd
../../dut/src/Filters/sharp_filter.vhd
../../dut/src/Filters/sharp_mac.vhd
../../dut/src/Filters/ccm.vhd
../../dut/src/Filters/coef_mult.vhd
../../dut/src/Filters/color_correction.vhd
../../dut/src/Filters/dither_filter.vhd
../../dut/src/Filters/hsl.vhd
../../dut/src/Filters/hsl_1range.vhd
../../dut/src/Filters/hsl_2range.vhd
../../dut/src/Filters/hsl_3range.vhd
../../dut/src/Filters/hsl_4range.vhd
../../dut/src/Filters/hsv.vhd
../../dut/src/Filters/hsvl.vhd
../../dut/src/Filters/hsvl_1range.vhd
../../dut/src/Filters/hsvl_2range.vhd
../../dut/src/Filters/hsvl_3range.vhd
../../dut/src/Filters/hsvl_4range.vhd
../../dut/src/Filters/rgb_inverted.vhd
../../dut/src/Filters/rgb_kernal_prod.vhd
../../dut/src/Filters/rgb_ycbcr.vhd
../../dut/src/Filters/kernel_core.vhd
../../dut/src/Filters/Kernel.vhd
../../dut/src/Filters/Filters.vhd

../../dut/src/Control/axis_external.vhd
../../dut/src/Control/buffer_controller.vhd
../../dut/src/Control/camera_raw_data.vhd
../../dut/src/Control/camera_raw_to_rgb.vhd
../../dut/src/Control/data_taps.vhd
../../dut/src/Control/frame_process.vhd
../../dut/src/Control/mWrRd.vhd
../../dut/src/Control/rgb_4taps.vhd
../../dut/src/Control/sign_fixed_resize.vhd
../../dut/src/Control/tap4Line.vhd
../../dut/src/Control/tapLine.vhd
../../dut/src/Control/tap_buffer.vhd
../../dut/src/Control/tap_lines.vhd
../../dut/src/Control/taps_controller.vhd
../../dut/src/Control/video_select.vhd
../../dut/src/Control/video_stream.vhd

../../dut/src/Process/TestPattern.vhd
../../dut/src/Process/avg_values.vhd
../../dut/src/Process/color_avg.vhd
../../dut/src/Process/color_space_limits.vhd
../../dut/src/Process/color_trim.vhd
../../dut/src/Process/d_valid.vhd
../../dut/src/Process/detect_pixel.vhd
../../dut/src/Process/digital_clock.vhd
../../dut/src/Process/edge_objects.vhd
../../dut/src/Process/font_rom.vhd
../../dut/src/Process/frame_mask.vhd
../../dut/src/Process/frame_mix.vhd
../../dut/src/Process/frame_remake.vhd
../../dut/src/Process/frame_testpattern.vhd
../../dut/src/Process/grid_lock_fifo.vhd
../../dut/src/Process/lum_values.vhd
../../dut/src/Process/pixel_cord.vhd
../../dut/src/Process/pixel_on_display.vhd
../../dut/src/Process/point_of_interest.vhd
../../dut/src/Process/raw_to_rgb.vhd
../../dut/src/Process/recolor_space_1.vhd
../../dut/src/Process/recolor_space_2.vhd
../../dut/src/Process/recolor_space_3.vhd
../../dut/src/Process/recolor_space_4.vhd
../../dut/src/Process/recolor_space_5.vhd
../../dut/src/Process/recolor_space_6.vhd
../../dut/src/Process/recolor_space_7.vhd
../../dut/src/Process/recolor_space_8.vhd
../../dut/src/Process/recolor_space_hsl.vhd
../../dut/src/Process/rgb_histogram.vhd
../../dut/src/Process/rgb_range.vhd
../../dut/src/Process/rgb_select.vhd
../../dut/src/Process/segment_colors.vhd
../../dut/src/Process/sync_frames.vhd
../../dut/src/Process/text_gen.vhd


../../dut/hdl/vfpTop.vhd
../../dut/hdl/vfp_config.vhd
../../dut/hdl/vfp_m_axis.vhd
../../dut/hdl/vfp_s_axis.vhd


../../dut/tb/ImagesReadWrite/imageRead.vhd
../../dut/tb/ImagesReadWrite/imageWrite.vhd
../../dut/tb/ImagesReadWrite/imageReadInterface.vhd

../../dut/src/Xip/ByteToFloat/sim/ByteToFloat.vhd
../../dut/src/Xip/ByteToFloat/ByteToFloatTop.vhd
../../dut/src/Xip/FloatMultiply/sim/FloatMultiply.vhd
../../dut/src/Xip/FloatMultiply/FloatMultiplyTop.vhd
../../dut/src/Xip/FloatToFixedv1/sim/FloatToFixedv1.vhd
../../dut/src/Xip/FloatToFixedv1/FloatToFixedv1Top.vhd
../../dut/src/Xip/WordToFloat/sim/WordToFloat.vhd
../../dut/src/Xip/WordToFloat/WordToFloatTop.vhd
../../dut/src/Xip/FixedToFloat/sim/fixedToFloat.vhd
../../dut/src/Xip/FloatToFixed/sim/floatToFixed.vhd
../../dut/src/Xip/SquareRoot/sim/squareRoot.vhd
../../dut/src/Xip/SquareRoot/squareRootTop.vhd
../../dut/src/Xip/SquareRoot/sim/squareRoot.vhd
../../dut/src/Xip/SquareRoot/squareRootTop.vhd
